spring:
  application:
    name: E-Prescription Core API
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
    
  jpa:
    hibernate:
      ddl-auto: update
