services:
  spring-boot-server:
    build: backend-server
    restart: unless-stopped
    volumes:
      - ./backend-server:/app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ePrescriptionServer_db 
      - SPRING_DATASOURCE_USERNAME=spring_user 
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgresql
      - keycloak
  

  postgresql:
    container_name: postgres
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak-server
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user 
      KC_DB_PASSWORD: keycloak_pass
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      KC_HTTP_PORT: 8081
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8081:8081"
    command: start-dev --import-realm
    depends_on:
      - postgresql
    
  frontend-client:
    build: frontend-client
    restart: unless-stopped
    volumes:
      - ./frontend-client:/app
    ports:
      - 4321:4321
    depends_on:
      - spring-boot-server

volumes:
  postgres_data: