services:
  spring-boot-server:
    build: backend-server
    restart: unless-stopped
    volumes:
      - ./backend-server:/app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eprescription_db
      
      - SPRING_DATASOURCE_USERNAME=user 
      
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres-db
  

  postgres-db:
    container_name: postgresql_database
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eprescription_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: